server {
<<<<<<< HEAD
  listen 3000;
  root /usr/share/nginx/html;
  index index.html;
  location / {
    try_files $uri /index.html;
  }
=======
    listen 3000;
    listen [::]:3000;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
>>>>>>> 0352910106950e8257be642c6d92f0ec1e9b5a6c
}

